# $Id: Makefile,v $Revision 2012/11/02 20:52:55 dhn Exp $

COMMENT=	Simple and very fast XML to hash conversion

MODULES=	cpan
USE_GROFF =	Yes

DISTNAME=	XML-Fast-0.11
CATEGORIES=	www textproc

# perl
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes
PERMIT_DISTFILES_CDROM=	Yes
PERMIT_DISTFILES_FTP=	Yes

.include <bsd.port.mk>
